package com.bt.om.entity;

import java.util.Date;

public class AppDownload {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_download.id
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_download.address
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_download.version
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	private String version;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_download.if_force
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	private Integer ifForce;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_download.describe
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	private String describe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_download.create_time
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column app_download.update_time
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_download.id
	 * @return  the value of app_download.id
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_download.id
	 * @param id  the value for app_download.id
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_download.address
	 * @return  the value of app_download.address
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_download.address
	 * @param address  the value for app_download.address
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_download.version
	 * @return  the value of app_download.version
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public String getVersion() {
		return version;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_download.version
	 * @param version  the value for app_download.version
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public void setVersion(String version) {
		this.version = version == null ? null : version.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_download.if_force
	 * @return  the value of app_download.if_force
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public Integer getIfForce() {
		return ifForce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_download.if_force
	 * @param ifForce  the value for app_download.if_force
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public void setIfForce(Integer ifForce) {
		this.ifForce = ifForce;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_download.describe
	 * @return  the value of app_download.describe
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public String getDescribe() {
		return describe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_download.describe
	 * @param describe  the value for app_download.describe
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public void setDescribe(String describe) {
		this.describe = describe == null ? null : describe.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_download.create_time
	 * @return  the value of app_download.create_time
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_download.create_time
	 * @param createTime  the value for app_download.create_time
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column app_download.update_time
	 * @return  the value of app_download.update_time
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column app_download.update_time
	 * @param updateTime  the value for app_download.update_time
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}