package com.bt.om.entity;

import java.util.Date;

public class Banner {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.id
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.img_url
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	private String imgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.link
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.width
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	private String width;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.hight
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	private String hight;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.target
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	private Integer target;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.type
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.status
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.valid_time
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	private Date validTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.create_time
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column banner.update_time
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.id
	 * @return  the value of banner.id
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.id
	 * @param id  the value for banner.id
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.img_url
	 * @return  the value of banner.img_url
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public String getImgUrl() {
		return imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.img_url
	 * @param imgUrl  the value for banner.img_url
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl == null ? null : imgUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.link
	 * @return  the value of banner.link
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.link
	 * @param link  the value for banner.link
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public void setLink(String link) {
		this.link = link == null ? null : link.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.width
	 * @return  the value of banner.width
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public String getWidth() {
		return width;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.width
	 * @param width  the value for banner.width
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public void setWidth(String width) {
		this.width = width == null ? null : width.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.hight
	 * @return  the value of banner.hight
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public String getHight() {
		return hight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.hight
	 * @param hight  the value for banner.hight
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public void setHight(String hight) {
		this.hight = hight == null ? null : hight.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.target
	 * @return  the value of banner.target
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public Integer getTarget() {
		return target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.target
	 * @param target  the value for banner.target
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public void setTarget(Integer target) {
		this.target = target;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.type
	 * @return  the value of banner.type
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.type
	 * @param type  the value for banner.type
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.status
	 * @return  the value of banner.status
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.status
	 * @param status  the value for banner.status
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.valid_time
	 * @return  the value of banner.valid_time
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public Date getValidTime() {
		return validTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.valid_time
	 * @param validTime  the value for banner.valid_time
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public void setValidTime(Date validTime) {
		this.validTime = validTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.create_time
	 * @return  the value of banner.create_time
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.create_time
	 * @param createTime  the value for banner.create_time
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column banner.update_time
	 * @return  the value of banner.update_time
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column banner.update_time
	 * @param updateTime  the value for banner.update_time
	 * @mbg.generated  Tue Jun 12 12:37:53 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}