package com.bt.om.entity;

import java.util.Date;

public class DrawCash{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash.id
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash.mobile
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash.alipay_account
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	private String alipayAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash.cash
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	private Double cash;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash.reward
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	private Integer reward;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash.status
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash.pay_time
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash.create_time
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash.update_time
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash.id
	 * @return  the value of draw_cash.id
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash.id
	 * @param id  the value for draw_cash.id
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash.mobile
	 * @return  the value of draw_cash.mobile
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash.mobile
	 * @param mobile  the value for draw_cash.mobile
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash.alipay_account
	 * @return  the value of draw_cash.alipay_account
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public String getAlipayAccount() {
		return alipayAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash.alipay_account
	 * @param alipayAccount  the value for draw_cash.alipay_account
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public void setAlipayAccount(String alipayAccount) {
		this.alipayAccount = alipayAccount == null ? null : alipayAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash.cash
	 * @return  the value of draw_cash.cash
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public Double getCash() {
		return cash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash.cash
	 * @param cash  the value for draw_cash.cash
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public void setCash(Double cash) {
		this.cash = cash;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash.reward
	 * @return  the value of draw_cash.reward
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public Integer getReward() {
		return reward;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash.reward
	 * @param reward  the value for draw_cash.reward
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public void setReward(Integer reward) {
		this.reward = reward;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash.status
	 * @return  the value of draw_cash.status
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash.status
	 * @param status  the value for draw_cash.status
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash.pay_time
	 * @return  the value of draw_cash.pay_time
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash.pay_time
	 * @param payTime  the value for draw_cash.pay_time
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash.create_time
	 * @return  the value of draw_cash.create_time
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash.create_time
	 * @param createTime  the value for draw_cash.create_time
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash.update_time
	 * @return  the value of draw_cash.update_time
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash.update_time
	 * @param updateTime  the value for draw_cash.update_time
	 * @mbg.generated  Sun Apr 29 11:11:54 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}