package com.bt.om.entity;

import java.util.Date;

public class DrawCashOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash_order.id
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash_order.draw_cach_id
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	private Integer drawCachId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash_order.order_id
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash_order.create_time
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column draw_cash_order.update_time
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash_order.id
	 * @return  the value of draw_cash_order.id
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash_order.id
	 * @param id  the value for draw_cash_order.id
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash_order.draw_cach_id
	 * @return  the value of draw_cash_order.draw_cach_id
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	public Integer getDrawCachId() {
		return drawCachId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash_order.draw_cach_id
	 * @param drawCachId  the value for draw_cash_order.draw_cach_id
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	public void setDrawCachId(Integer drawCachId) {
		this.drawCachId = drawCachId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash_order.order_id
	 * @return  the value of draw_cash_order.order_id
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash_order.order_id
	 * @param orderId  the value for draw_cash_order.order_id
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash_order.create_time
	 * @return  the value of draw_cash_order.create_time
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash_order.create_time
	 * @param createTime  the value for draw_cash_order.create_time
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column draw_cash_order.update_time
	 * @return  the value of draw_cash_order.update_time
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column draw_cash_order.update_time
	 * @param updateTime  the value for draw_cash_order.update_time
	 * @mbg.generated  Wed Apr 25 16:09:02 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}