package com.bt.om.entity;

import java.util.Date;

public class Hotword {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotword.id
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotword.word
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotword.create_time
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotword.update_time
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotword.id
     *
     * @return the value of hotword.id
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotword.id
     *
     * @param id the value for hotword.id
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotword.word
     *
     * @return the value of hotword.word
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotword.word
     *
     * @param word the value for hotword.word
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    public void setWord(String word) {
        this.word = word == null ? null : word.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotword.create_time
     *
     * @return the value of hotword.create_time
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotword.create_time
     *
     * @param createTime the value for hotword.create_time
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotword.update_time
     *
     * @return the value of hotword.update_time
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotword.update_time
     *
     * @param updateTime the value for hotword.update_time
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}