package com.bt.om.entity;

import java.util.Date;

public class Notice {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.id
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.type
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.title
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.content
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.status
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.create_time
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column notice.update_time
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.id
	 * @return  the value of notice.id
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.id
	 * @param id  the value for notice.id
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.type
	 * @return  the value of notice.type
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.type
	 * @param type  the value for notice.type
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.title
	 * @return  the value of notice.title
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.title
	 * @param title  the value for notice.title
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.content
	 * @return  the value of notice.content
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.content
	 * @param content  the value for notice.content
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.status
	 * @return  the value of notice.status
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.status
	 * @param status  the value for notice.status
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.create_time
	 * @return  the value of notice.create_time
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.create_time
	 * @param createTime  the value for notice.create_time
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column notice.update_time
	 * @return  the value of notice.update_time
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column notice.update_time
	 * @param updateTime  the value for notice.update_time
	 * @mbg.generated  Tue May 22 15:41:38 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}