package com.bt.om.entity;

import java.util.Date;

public class PddPids {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdd_pids.id
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdd_pids.create_time
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdd_pids.pdd_id
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	private String pddId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdd_pids.pid
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	private String pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdd_pids.pid_name
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	private String pidName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pdd_pids.customer_id
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	private String customerId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdd_pids.id
	 * @return  the value of pdd_pids.id
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdd_pids.id
	 * @param id  the value for pdd_pids.id
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdd_pids.create_time
	 * @return  the value of pdd_pids.create_time
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdd_pids.create_time
	 * @param createTime  the value for pdd_pids.create_time
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdd_pids.pdd_id
	 * @return  the value of pdd_pids.pdd_id
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public String getPddId() {
		return pddId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdd_pids.pdd_id
	 * @param pddId  the value for pdd_pids.pdd_id
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public void setPddId(String pddId) {
		this.pddId = pddId == null ? null : pddId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdd_pids.pid
	 * @return  the value of pdd_pids.pid
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdd_pids.pid
	 * @param pid  the value for pdd_pids.pid
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public void setPid(String pid) {
		this.pid = pid == null ? null : pid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdd_pids.pid_name
	 * @return  the value of pdd_pids.pid_name
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public String getPidName() {
		return pidName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdd_pids.pid_name
	 * @param pidName  the value for pdd_pids.pid_name
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public void setPidName(String pidName) {
		this.pidName = pidName == null ? null : pidName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pdd_pids.customer_id
	 * @return  the value of pdd_pids.customer_id
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public String getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pdd_pids.customer_id
	 * @param customerId  the value for pdd_pids.customer_id
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	public void setCustomerId(String customerId) {
		this.customerId = customerId == null ? null : customerId.trim();
	}
}