package com.bt.om.entity;

public class ProductFromTkapi{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.num_iid
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private Long numIid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.title
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.pict_url
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private String pictUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.small_images
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private String smallImages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.reserve_price
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private String reservePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.zk_final_price
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private String zkFinalPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.user_type
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private Integer userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.provcity
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private String provcity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.item_url
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private String itemUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.nick
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private String nick;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.seller_id
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private String sellerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.volume
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private Integer volume;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product_from_tkapi.skey
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	private String skey;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.num_iid
	 * @return  the value of product_from_tkapi.num_iid
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public Long getNumIid() {
		return numIid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.num_iid
	 * @param numIid  the value for product_from_tkapi.num_iid
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setNumIid(Long numIid) {
		this.numIid = numIid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.title
	 * @return  the value of product_from_tkapi.title
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.title
	 * @param title  the value for product_from_tkapi.title
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.pict_url
	 * @return  the value of product_from_tkapi.pict_url
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public String getPictUrl() {
		return pictUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.pict_url
	 * @param pictUrl  the value for product_from_tkapi.pict_url
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setPictUrl(String pictUrl) {
		this.pictUrl = pictUrl == null ? null : pictUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.small_images
	 * @return  the value of product_from_tkapi.small_images
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public String getSmallImages() {
		return smallImages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.small_images
	 * @param smallImages  the value for product_from_tkapi.small_images
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setSmallImages(String smallImages) {
		this.smallImages = smallImages == null ? null : smallImages.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.reserve_price
	 * @return  the value of product_from_tkapi.reserve_price
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public String getReservePrice() {
		return reservePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.reserve_price
	 * @param reservePrice  the value for product_from_tkapi.reserve_price
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setReservePrice(String reservePrice) {
		this.reservePrice = reservePrice == null ? null : reservePrice.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.zk_final_price
	 * @return  the value of product_from_tkapi.zk_final_price
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public String getZkFinalPrice() {
		return zkFinalPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.zk_final_price
	 * @param zkFinalPrice  the value for product_from_tkapi.zk_final_price
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setZkFinalPrice(String zkFinalPrice) {
		this.zkFinalPrice = zkFinalPrice == null ? null : zkFinalPrice.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.user_type
	 * @return  the value of product_from_tkapi.user_type
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public Integer getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.user_type
	 * @param userType  the value for product_from_tkapi.user_type
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.provcity
	 * @return  the value of product_from_tkapi.provcity
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public String getProvcity() {
		return provcity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.provcity
	 * @param provcity  the value for product_from_tkapi.provcity
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setProvcity(String provcity) {
		this.provcity = provcity == null ? null : provcity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.item_url
	 * @return  the value of product_from_tkapi.item_url
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public String getItemUrl() {
		return itemUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.item_url
	 * @param itemUrl  the value for product_from_tkapi.item_url
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setItemUrl(String itemUrl) {
		this.itemUrl = itemUrl == null ? null : itemUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.nick
	 * @return  the value of product_from_tkapi.nick
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public String getNick() {
		return nick;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.nick
	 * @param nick  the value for product_from_tkapi.nick
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setNick(String nick) {
		this.nick = nick == null ? null : nick.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.seller_id
	 * @return  the value of product_from_tkapi.seller_id
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public String getSellerId() {
		return sellerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.seller_id
	 * @param sellerId  the value for product_from_tkapi.seller_id
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setSellerId(String sellerId) {
		this.sellerId = sellerId == null ? null : sellerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.volume
	 * @return  the value of product_from_tkapi.volume
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public Integer getVolume() {
		return volume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.volume
	 * @param volume  the value for product_from_tkapi.volume
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setVolume(Integer volume) {
		this.volume = volume;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product_from_tkapi.skey
	 * @return  the value of product_from_tkapi.skey
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public String getSkey() {
		return skey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product_from_tkapi.skey
	 * @param skey  the value for product_from_tkapi.skey
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	public void setSkey(String skey) {
		this.skey = skey == null ? null : skey.trim();
	}
}