package com.bt.om.entity;

import java.util.Date;

public class SearchRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.id
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.mobile
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.title
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.status
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.create_time
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column search_record.update_time
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.id
     *
     * @return the value of search_record.id
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.id
     *
     * @param id the value for search_record.id
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.mobile
     *
     * @return the value of search_record.mobile
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.mobile
     *
     * @param mobile the value for search_record.mobile
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.title
     *
     * @return the value of search_record.title
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.title
     *
     * @param title the value for search_record.title
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.status
     *
     * @return the value of search_record.status
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.status
     *
     * @param status the value for search_record.status
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.create_time
     *
     * @return the value of search_record.create_time
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.create_time
     *
     * @param createTime the value for search_record.create_time
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column search_record.update_time
     *
     * @return the value of search_record.update_time
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column search_record.update_time
     *
     * @param updateTime the value for search_record.update_time
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}