package com.bt.om.entity;

import java.util.Date;

public class SettleInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_info.id
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_info.mobile
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_info.type
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_info.money
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    private Float money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column settle_info.settle_time
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    private Date settleTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_info.id
     *
     * @return the value of settle_info.id
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_info.id
     *
     * @param id the value for settle_info.id
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_info.mobile
     *
     * @return the value of settle_info.mobile
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_info.mobile
     *
     * @param mobile the value for settle_info.mobile
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_info.type
     *
     * @return the value of settle_info.type
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_info.type
     *
     * @param type the value for settle_info.type
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_info.money
     *
     * @return the value of settle_info.money
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    public Float getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_info.money
     *
     * @param money the value for settle_info.money
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    public void setMoney(Float money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column settle_info.settle_time
     *
     * @return the value of settle_info.settle_time
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    public Date getSettleTime() {
        return settleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column settle_info.settle_time
     *
     * @param settleTime the value for settle_info.settle_time
     *
     * @mbg.generated Sat Nov 17 21:53:08 CST 2018
     */
    public void setSettleTime(Date settleTime) {
        this.settleTime = settleTime;
    }
}