package com.bt.om.entity;

import java.util.Date;

public class SmsPushStats {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_push_stats.id
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_push_stats.ip
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_push_stats.type
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_push_stats.create_time
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_push_stats.id
     *
     * @return the value of sms_push_stats.id
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_push_stats.id
     *
     * @param id the value for sms_push_stats.id
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_push_stats.ip
     *
     * @return the value of sms_push_stats.ip
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_push_stats.ip
     *
     * @param ip the value for sms_push_stats.ip
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_push_stats.type
     *
     * @return the value of sms_push_stats.type
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_push_stats.type
     *
     * @param type the value for sms_push_stats.type
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_push_stats.create_time
     *
     * @return the value of sms_push_stats.create_time
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_push_stats.create_time
     *
     * @param createTime the value for sms_push_stats.create_time
     *
     * @mbg.generated Thu Nov 15 12:36:49 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}