package com.bt.om.entity;

import java.util.Date;

public class SysUserDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_detail.id
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_detail.user_id
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_detail.alipay_account
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	private String alipayAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_detail.alipay_name
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	private String alipayName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_detail.weixin_account
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	private String weixinAccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_detail.create_time
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_user_detail.update_time
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_detail.id
	 * @return  the value of sys_user_detail.id
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_detail.id
	 * @param id  the value for sys_user_detail.id
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_detail.user_id
	 * @return  the value of sys_user_detail.user_id
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_detail.user_id
	 * @param userId  the value for sys_user_detail.user_id
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_detail.alipay_account
	 * @return  the value of sys_user_detail.alipay_account
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public String getAlipayAccount() {
		return alipayAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_detail.alipay_account
	 * @param alipayAccount  the value for sys_user_detail.alipay_account
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public void setAlipayAccount(String alipayAccount) {
		this.alipayAccount = alipayAccount == null ? null : alipayAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_detail.alipay_name
	 * @return  the value of sys_user_detail.alipay_name
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public String getAlipayName() {
		return alipayName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_detail.alipay_name
	 * @param alipayName  the value for sys_user_detail.alipay_name
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public void setAlipayName(String alipayName) {
		this.alipayName = alipayName == null ? null : alipayName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_detail.weixin_account
	 * @return  the value of sys_user_detail.weixin_account
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public String getWeixinAccount() {
		return weixinAccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_detail.weixin_account
	 * @param weixinAccount  the value for sys_user_detail.weixin_account
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public void setWeixinAccount(String weixinAccount) {
		this.weixinAccount = weixinAccount == null ? null : weixinAccount.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_detail.create_time
	 * @return  the value of sys_user_detail.create_time
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_detail.create_time
	 * @param createTime  the value for sys_user_detail.create_time
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_user_detail.update_time
	 * @return  the value of sys_user_detail.update_time
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_user_detail.update_time
	 * @param updateTime  the value for sys_user_detail.update_time
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}