package com.bt.om.entity;

public class TaobaoPids {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column taobao_pids.id
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column taobao_pids.pid
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	private String pid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column taobao_pids.pid1
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	private String pid1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column taobao_pids.site
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	private String site;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column taobao_pids.account
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	private String account;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column taobao_pids.id
	 * @return  the value of taobao_pids.id
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column taobao_pids.id
	 * @param id  the value for taobao_pids.id
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column taobao_pids.pid
	 * @return  the value of taobao_pids.pid
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column taobao_pids.pid
	 * @param pid  the value for taobao_pids.pid
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	public void setPid(String pid) {
		this.pid = pid == null ? null : pid.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column taobao_pids.pid1
	 * @return  the value of taobao_pids.pid1
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	public String getPid1() {
		return pid1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column taobao_pids.pid1
	 * @param pid1  the value for taobao_pids.pid1
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	public void setPid1(String pid1) {
		this.pid1 = pid1 == null ? null : pid1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column taobao_pids.site
	 * @return  the value of taobao_pids.site
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	public String getSite() {
		return site;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column taobao_pids.site
	 * @param site  the value for taobao_pids.site
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	public void setSite(String site) {
		this.site = site == null ? null : site.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column taobao_pids.account
	 * @return  the value of taobao_pids.account
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	public String getAccount() {
		return account;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column taobao_pids.account
	 * @param account  the value for taobao_pids.account
	 * @mbg.generated  Thu Dec 27 09:08:15 CST 2018
	 */
	public void setAccount(String account) {
		this.account = account == null ? null : account.trim();
	}
}