package com.bt.om.entity;

import java.util.Date;

public class TkInfoTask {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.id
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.shop_name
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private String shopName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.product_name
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.product_url
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private String productUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.type
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.sign
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private String sign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.status
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.product_img_url
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private String productImgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.price
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.sales
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private Integer sales;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.commision
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private Double commision;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.rate
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private Double rate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.quan_url
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private String quanUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.quan_mianzhi
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private Double quanMianzhi;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.quan_nums
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private Integer quanNums;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.tkurl
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private String tkurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.tcode
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private String tcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.quan_code
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private String quanCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.create_time
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_info_task.update_time
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.id
	 * @return  the value of tk_info_task.id
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.id
	 * @param id  the value for tk_info_task.id
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.shop_name
	 * @return  the value of tk_info_task.shop_name
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public String getShopName() {
		return shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.shop_name
	 * @param shopName  the value for tk_info_task.shop_name
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName == null ? null : shopName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.product_name
	 * @return  the value of tk_info_task.product_name
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.product_name
	 * @param productName  the value for tk_info_task.product_name
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setProductName(String productName) {
		this.productName = productName == null ? null : productName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.product_url
	 * @return  the value of tk_info_task.product_url
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public String getProductUrl() {
		return productUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.product_url
	 * @param productUrl  the value for tk_info_task.product_url
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setProductUrl(String productUrl) {
		this.productUrl = productUrl == null ? null : productUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.type
	 * @return  the value of tk_info_task.type
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.type
	 * @param type  the value for tk_info_task.type
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.sign
	 * @return  the value of tk_info_task.sign
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public String getSign() {
		return sign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.sign
	 * @param sign  the value for tk_info_task.sign
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setSign(String sign) {
		this.sign = sign == null ? null : sign.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.status
	 * @return  the value of tk_info_task.status
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.status
	 * @param status  the value for tk_info_task.status
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.product_img_url
	 * @return  the value of tk_info_task.product_img_url
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public String getProductImgUrl() {
		return productImgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.product_img_url
	 * @param productImgUrl  the value for tk_info_task.product_img_url
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setProductImgUrl(String productImgUrl) {
		this.productImgUrl = productImgUrl == null ? null : productImgUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.price
	 * @return  the value of tk_info_task.price
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.price
	 * @param price  the value for tk_info_task.price
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.sales
	 * @return  the value of tk_info_task.sales
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public Integer getSales() {
		return sales;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.sales
	 * @param sales  the value for tk_info_task.sales
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setSales(Integer sales) {
		this.sales = sales;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.commision
	 * @return  the value of tk_info_task.commision
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public Double getCommision() {
		return commision;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.commision
	 * @param commision  the value for tk_info_task.commision
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setCommision(Double commision) {
		this.commision = commision;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.rate
	 * @return  the value of tk_info_task.rate
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public Double getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.rate
	 * @param rate  the value for tk_info_task.rate
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setRate(Double rate) {
		this.rate = rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.quan_url
	 * @return  the value of tk_info_task.quan_url
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public String getQuanUrl() {
		return quanUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.quan_url
	 * @param quanUrl  the value for tk_info_task.quan_url
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setQuanUrl(String quanUrl) {
		this.quanUrl = quanUrl == null ? null : quanUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.quan_mianzhi
	 * @return  the value of tk_info_task.quan_mianzhi
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public Double getQuanMianzhi() {
		return quanMianzhi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.quan_mianzhi
	 * @param quanMianzhi  the value for tk_info_task.quan_mianzhi
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setQuanMianzhi(Double quanMianzhi) {
		this.quanMianzhi = quanMianzhi;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.quan_nums
	 * @return  the value of tk_info_task.quan_nums
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public Integer getQuanNums() {
		return quanNums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.quan_nums
	 * @param quanNums  the value for tk_info_task.quan_nums
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setQuanNums(Integer quanNums) {
		this.quanNums = quanNums;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.tkurl
	 * @return  the value of tk_info_task.tkurl
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public String getTkurl() {
		return tkurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.tkurl
	 * @param tkurl  the value for tk_info_task.tkurl
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setTkurl(String tkurl) {
		this.tkurl = tkurl == null ? null : tkurl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.tcode
	 * @return  the value of tk_info_task.tcode
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public String getTcode() {
		return tcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.tcode
	 * @param tcode  the value for tk_info_task.tcode
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setTcode(String tcode) {
		this.tcode = tcode == null ? null : tcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.quan_code
	 * @return  the value of tk_info_task.quan_code
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public String getQuanCode() {
		return quanCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.quan_code
	 * @param quanCode  the value for tk_info_task.quan_code
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setQuanCode(String quanCode) {
		this.quanCode = quanCode == null ? null : quanCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.create_time
	 * @return  the value of tk_info_task.create_time
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.create_time
	 * @param createTime  the value for tk_info_task.create_time
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_info_task.update_time
	 * @return  the value of tk_info_task.update_time
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_info_task.update_time
	 * @param updateTime  the value for tk_info_task.update_time
	 * @mbg.generated  Sun Apr 22 13:08:47 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}