package com.bt.om.entity;

import java.util.Date;

public class TkOrderInput {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.create_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.click_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String clickTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.product_info
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String productInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.product_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.seller_wangwang
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String sellerWangwang;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.shop_name
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String shopName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.product_num
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Integer productNum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.price
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.order_status
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.order_type
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String orderType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.income_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Double incomeRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.divide_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Double divideRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.pay_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Double payMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.effect_estimate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Double effectEstimate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.settle_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Double settleMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.estimate_income
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Double estimateIncome;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.settle_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String settleTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.commission_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Double commissionRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.commission_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Double commissionMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.subsidy_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Double subsidyRate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.subsidy_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Double subsidyMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.subsidy_type
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String subsidyType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.deal_platform
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String dealPlatform;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.third_service_from
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String thirdServiceFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.order_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.cat_name
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String catName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.source_media_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String sourceMediaId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.ad_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String adId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.ad_name
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private String adName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column tk_order_input.update_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.id
	 * @return  the value of tk_order_input.id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.id
	 * @param id  the value for tk_order_input.id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.create_time
	 * @return  the value of tk_order_input.create_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.create_time
	 * @param createTime  the value for tk_order_input.create_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime == null ? null : createTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.click_time
	 * @return  the value of tk_order_input.click_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getClickTime() {
		return clickTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.click_time
	 * @param clickTime  the value for tk_order_input.click_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setClickTime(String clickTime) {
		this.clickTime = clickTime == null ? null : clickTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.product_info
	 * @return  the value of tk_order_input.product_info
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getProductInfo() {
		return productInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.product_info
	 * @param productInfo  the value for tk_order_input.product_info
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setProductInfo(String productInfo) {
		this.productInfo = productInfo == null ? null : productInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.product_id
	 * @return  the value of tk_order_input.product_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.product_id
	 * @param productId  the value for tk_order_input.product_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setProductId(String productId) {
		this.productId = productId == null ? null : productId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.seller_wangwang
	 * @return  the value of tk_order_input.seller_wangwang
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getSellerWangwang() {
		return sellerWangwang;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.seller_wangwang
	 * @param sellerWangwang  the value for tk_order_input.seller_wangwang
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setSellerWangwang(String sellerWangwang) {
		this.sellerWangwang = sellerWangwang == null ? null : sellerWangwang.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.shop_name
	 * @return  the value of tk_order_input.shop_name
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getShopName() {
		return shopName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.shop_name
	 * @param shopName  the value for tk_order_input.shop_name
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setShopName(String shopName) {
		this.shopName = shopName == null ? null : shopName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.product_num
	 * @return  the value of tk_order_input.product_num
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Integer getProductNum() {
		return productNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.product_num
	 * @param productNum  the value for tk_order_input.product_num
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setProductNum(Integer productNum) {
		this.productNum = productNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.price
	 * @return  the value of tk_order_input.price
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.price
	 * @param price  the value for tk_order_input.price
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.order_status
	 * @return  the value of tk_order_input.order_status
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.order_status
	 * @param orderStatus  the value for tk_order_input.order_status
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus == null ? null : orderStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.order_type
	 * @return  the value of tk_order_input.order_type
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.order_type
	 * @param orderType  the value for tk_order_input.order_type
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setOrderType(String orderType) {
		this.orderType = orderType == null ? null : orderType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.income_rate
	 * @return  the value of tk_order_input.income_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Double getIncomeRate() {
		return incomeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.income_rate
	 * @param incomeRate  the value for tk_order_input.income_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setIncomeRate(Double incomeRate) {
		this.incomeRate = incomeRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.divide_rate
	 * @return  the value of tk_order_input.divide_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Double getDivideRate() {
		return divideRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.divide_rate
	 * @param divideRate  the value for tk_order_input.divide_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setDivideRate(Double divideRate) {
		this.divideRate = divideRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.pay_money
	 * @return  the value of tk_order_input.pay_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Double getPayMoney() {
		return payMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.pay_money
	 * @param payMoney  the value for tk_order_input.pay_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setPayMoney(Double payMoney) {
		this.payMoney = payMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.effect_estimate
	 * @return  the value of tk_order_input.effect_estimate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Double getEffectEstimate() {
		return effectEstimate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.effect_estimate
	 * @param effectEstimate  the value for tk_order_input.effect_estimate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setEffectEstimate(Double effectEstimate) {
		this.effectEstimate = effectEstimate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.settle_money
	 * @return  the value of tk_order_input.settle_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Double getSettleMoney() {
		return settleMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.settle_money
	 * @param settleMoney  the value for tk_order_input.settle_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setSettleMoney(Double settleMoney) {
		this.settleMoney = settleMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.estimate_income
	 * @return  the value of tk_order_input.estimate_income
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Double getEstimateIncome() {
		return estimateIncome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.estimate_income
	 * @param estimateIncome  the value for tk_order_input.estimate_income
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setEstimateIncome(Double estimateIncome) {
		this.estimateIncome = estimateIncome;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.settle_time
	 * @return  the value of tk_order_input.settle_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getSettleTime() {
		return settleTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.settle_time
	 * @param settleTime  the value for tk_order_input.settle_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setSettleTime(String settleTime) {
		this.settleTime = settleTime == null ? null : settleTime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.commission_rate
	 * @return  the value of tk_order_input.commission_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Double getCommissionRate() {
		return commissionRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.commission_rate
	 * @param commissionRate  the value for tk_order_input.commission_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setCommissionRate(Double commissionRate) {
		this.commissionRate = commissionRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.commission_money
	 * @return  the value of tk_order_input.commission_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Double getCommissionMoney() {
		return commissionMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.commission_money
	 * @param commissionMoney  the value for tk_order_input.commission_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setCommissionMoney(Double commissionMoney) {
		this.commissionMoney = commissionMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.subsidy_rate
	 * @return  the value of tk_order_input.subsidy_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Double getSubsidyRate() {
		return subsidyRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.subsidy_rate
	 * @param subsidyRate  the value for tk_order_input.subsidy_rate
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setSubsidyRate(Double subsidyRate) {
		this.subsidyRate = subsidyRate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.subsidy_money
	 * @return  the value of tk_order_input.subsidy_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Double getSubsidyMoney() {
		return subsidyMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.subsidy_money
	 * @param subsidyMoney  the value for tk_order_input.subsidy_money
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setSubsidyMoney(Double subsidyMoney) {
		this.subsidyMoney = subsidyMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.subsidy_type
	 * @return  the value of tk_order_input.subsidy_type
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getSubsidyType() {
		return subsidyType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.subsidy_type
	 * @param subsidyType  the value for tk_order_input.subsidy_type
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setSubsidyType(String subsidyType) {
		this.subsidyType = subsidyType == null ? null : subsidyType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.deal_platform
	 * @return  the value of tk_order_input.deal_platform
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getDealPlatform() {
		return dealPlatform;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.deal_platform
	 * @param dealPlatform  the value for tk_order_input.deal_platform
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setDealPlatform(String dealPlatform) {
		this.dealPlatform = dealPlatform == null ? null : dealPlatform.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.third_service_from
	 * @return  the value of tk_order_input.third_service_from
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getThirdServiceFrom() {
		return thirdServiceFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.third_service_from
	 * @param thirdServiceFrom  the value for tk_order_input.third_service_from
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setThirdServiceFrom(String thirdServiceFrom) {
		this.thirdServiceFrom = thirdServiceFrom == null ? null : thirdServiceFrom.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.order_id
	 * @return  the value of tk_order_input.order_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.order_id
	 * @param orderId  the value for tk_order_input.order_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.cat_name
	 * @return  the value of tk_order_input.cat_name
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getCatName() {
		return catName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.cat_name
	 * @param catName  the value for tk_order_input.cat_name
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setCatName(String catName) {
		this.catName = catName == null ? null : catName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.source_media_id
	 * @return  the value of tk_order_input.source_media_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getSourceMediaId() {
		return sourceMediaId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.source_media_id
	 * @param sourceMediaId  the value for tk_order_input.source_media_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setSourceMediaId(String sourceMediaId) {
		this.sourceMediaId = sourceMediaId == null ? null : sourceMediaId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.ad_id
	 * @return  the value of tk_order_input.ad_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getAdId() {
		return adId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.ad_id
	 * @param adId  the value for tk_order_input.ad_id
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setAdId(String adId) {
		this.adId = adId == null ? null : adId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.ad_name
	 * @return  the value of tk_order_input.ad_name
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public String getAdName() {
		return adName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.ad_name
	 * @param adName  the value for tk_order_input.ad_name
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setAdName(String adName) {
		this.adName = adName == null ? null : adName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column tk_order_input.update_time
	 * @return  the value of tk_order_input.update_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column tk_order_input.update_time
	 * @param updateTime  the value for tk_order_input.update_time
	 * @mbg.generated  Wed May 02 19:56:16 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}