package com.bt.om.entity;

import java.util.Date;

public class TkOrderLastRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_last_record.id
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_last_record.platform
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    private Integer platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_last_record.order_time
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    private String orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_last_record.create_time
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_last_record.update_time
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_last_record.id
     *
     * @return the value of tk_order_last_record.id
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_last_record.id
     *
     * @param id the value for tk_order_last_record.id
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_last_record.platform
     *
     * @return the value of tk_order_last_record.platform
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    public Integer getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_last_record.platform
     *
     * @param platform the value for tk_order_last_record.platform
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    public void setPlatform(Integer platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_last_record.order_time
     *
     * @return the value of tk_order_last_record.order_time
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_last_record.order_time
     *
     * @param orderTime the value for tk_order_last_record.order_time
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_last_record.create_time
     *
     * @return the value of tk_order_last_record.create_time
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_last_record.create_time
     *
     * @param createTime the value for tk_order_last_record.create_time
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_last_record.update_time
     *
     * @return the value of tk_order_last_record.update_time
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_last_record.update_time
     *
     * @param updateTime the value for tk_order_last_record.update_time
     *
     * @mbg.generated Wed May 02 16:01:55 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}