package com.bt.om.entity;

public class TkOrderInputJd {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.order_time
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String orderTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.order_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.product_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.product_name
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.price
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.product_num
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Integer productNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.after_sale_num
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Integer afterSaleNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.rejected_num
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Integer rejectedNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.order_status
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.commission_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Double commissionRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.divide_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Double divideRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.subsidy_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Double subsidyRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.subsidy_type
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String subsidyType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.actual_divide_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Double actualDivideRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.estimate_money
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Double estimateMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.estimate_commission
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Double estimateCommission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.complete_time
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String completeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.actual_money
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Double actualMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.actual_commission
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private Double actualCommission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.settle_time
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String settleTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.platform_type
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String platformType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.plus_order
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String plusOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.tongkuadian
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String tongkuadian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.father_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String fatherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.ad_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String adId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.ad_name
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String adName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.channel
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String channel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.third_service_from
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String thirdServiceFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.pid
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tk_order_input_jd.site_app
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    private String siteApp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.id
     *
     * @return the value of tk_order_input_jd.id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.id
     *
     * @param id the value for tk_order_input_jd.id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.order_time
     *
     * @return the value of tk_order_input_jd.order_time
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.order_time
     *
     * @param orderTime the value for tk_order_input_jd.order_time
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setOrderTime(String orderTime) {
        this.orderTime = orderTime == null ? null : orderTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.order_id
     *
     * @return the value of tk_order_input_jd.order_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.order_id
     *
     * @param orderId the value for tk_order_input_jd.order_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.product_id
     *
     * @return the value of tk_order_input_jd.product_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.product_id
     *
     * @param productId the value for tk_order_input_jd.product_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.product_name
     *
     * @return the value of tk_order_input_jd.product_name
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.product_name
     *
     * @param productName the value for tk_order_input_jd.product_name
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.price
     *
     * @return the value of tk_order_input_jd.price
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.price
     *
     * @param price the value for tk_order_input_jd.price
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.product_num
     *
     * @return the value of tk_order_input_jd.product_num
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Integer getProductNum() {
        return productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.product_num
     *
     * @param productNum the value for tk_order_input_jd.product_num
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.after_sale_num
     *
     * @return the value of tk_order_input_jd.after_sale_num
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Integer getAfterSaleNum() {
        return afterSaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.after_sale_num
     *
     * @param afterSaleNum the value for tk_order_input_jd.after_sale_num
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setAfterSaleNum(Integer afterSaleNum) {
        this.afterSaleNum = afterSaleNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.rejected_num
     *
     * @return the value of tk_order_input_jd.rejected_num
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Integer getRejectedNum() {
        return rejectedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.rejected_num
     *
     * @param rejectedNum the value for tk_order_input_jd.rejected_num
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setRejectedNum(Integer rejectedNum) {
        this.rejectedNum = rejectedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.order_status
     *
     * @return the value of tk_order_input_jd.order_status
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.order_status
     *
     * @param orderStatus the value for tk_order_input_jd.order_status
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus == null ? null : orderStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.commission_rate
     *
     * @return the value of tk_order_input_jd.commission_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Double getCommissionRate() {
        return commissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.commission_rate
     *
     * @param commissionRate the value for tk_order_input_jd.commission_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setCommissionRate(Double commissionRate) {
        this.commissionRate = commissionRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.divide_rate
     *
     * @return the value of tk_order_input_jd.divide_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Double getDivideRate() {
        return divideRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.divide_rate
     *
     * @param divideRate the value for tk_order_input_jd.divide_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setDivideRate(Double divideRate) {
        this.divideRate = divideRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.subsidy_rate
     *
     * @return the value of tk_order_input_jd.subsidy_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Double getSubsidyRate() {
        return subsidyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.subsidy_rate
     *
     * @param subsidyRate the value for tk_order_input_jd.subsidy_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setSubsidyRate(Double subsidyRate) {
        this.subsidyRate = subsidyRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.subsidy_type
     *
     * @return the value of tk_order_input_jd.subsidy_type
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getSubsidyType() {
        return subsidyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.subsidy_type
     *
     * @param subsidyType the value for tk_order_input_jd.subsidy_type
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setSubsidyType(String subsidyType) {
        this.subsidyType = subsidyType == null ? null : subsidyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.actual_divide_rate
     *
     * @return the value of tk_order_input_jd.actual_divide_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Double getActualDivideRate() {
        return actualDivideRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.actual_divide_rate
     *
     * @param actualDivideRate the value for tk_order_input_jd.actual_divide_rate
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setActualDivideRate(Double actualDivideRate) {
        this.actualDivideRate = actualDivideRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.estimate_money
     *
     * @return the value of tk_order_input_jd.estimate_money
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Double getEstimateMoney() {
        return estimateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.estimate_money
     *
     * @param estimateMoney the value for tk_order_input_jd.estimate_money
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setEstimateMoney(Double estimateMoney) {
        this.estimateMoney = estimateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.estimate_commission
     *
     * @return the value of tk_order_input_jd.estimate_commission
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Double getEstimateCommission() {
        return estimateCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.estimate_commission
     *
     * @param estimateCommission the value for tk_order_input_jd.estimate_commission
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setEstimateCommission(Double estimateCommission) {
        this.estimateCommission = estimateCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.complete_time
     *
     * @return the value of tk_order_input_jd.complete_time
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.complete_time
     *
     * @param completeTime the value for tk_order_input_jd.complete_time
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setCompleteTime(String completeTime) {
        this.completeTime = completeTime == null ? null : completeTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.actual_money
     *
     * @return the value of tk_order_input_jd.actual_money
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Double getActualMoney() {
        return actualMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.actual_money
     *
     * @param actualMoney the value for tk_order_input_jd.actual_money
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setActualMoney(Double actualMoney) {
        this.actualMoney = actualMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.actual_commission
     *
     * @return the value of tk_order_input_jd.actual_commission
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public Double getActualCommission() {
        return actualCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.actual_commission
     *
     * @param actualCommission the value for tk_order_input_jd.actual_commission
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setActualCommission(Double actualCommission) {
        this.actualCommission = actualCommission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.settle_time
     *
     * @return the value of tk_order_input_jd.settle_time
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getSettleTime() {
        return settleTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.settle_time
     *
     * @param settleTime the value for tk_order_input_jd.settle_time
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setSettleTime(String settleTime) {
        this.settleTime = settleTime == null ? null : settleTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.platform_type
     *
     * @return the value of tk_order_input_jd.platform_type
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getPlatformType() {
        return platformType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.platform_type
     *
     * @param platformType the value for tk_order_input_jd.platform_type
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setPlatformType(String platformType) {
        this.platformType = platformType == null ? null : platformType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.plus_order
     *
     * @return the value of tk_order_input_jd.plus_order
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getPlusOrder() {
        return plusOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.plus_order
     *
     * @param plusOrder the value for tk_order_input_jd.plus_order
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setPlusOrder(String plusOrder) {
        this.plusOrder = plusOrder == null ? null : plusOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.tongkuadian
     *
     * @return the value of tk_order_input_jd.tongkuadian
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getTongkuadian() {
        return tongkuadian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.tongkuadian
     *
     * @param tongkuadian the value for tk_order_input_jd.tongkuadian
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setTongkuadian(String tongkuadian) {
        this.tongkuadian = tongkuadian == null ? null : tongkuadian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.father_id
     *
     * @return the value of tk_order_input_jd.father_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.father_id
     *
     * @param fatherId the value for tk_order_input_jd.father_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setFatherId(String fatherId) {
        this.fatherId = fatherId == null ? null : fatherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.ad_id
     *
     * @return the value of tk_order_input_jd.ad_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getAdId() {
        return adId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.ad_id
     *
     * @param adId the value for tk_order_input_jd.ad_id
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setAdId(String adId) {
        this.adId = adId == null ? null : adId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.ad_name
     *
     * @return the value of tk_order_input_jd.ad_name
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getAdName() {
        return adName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.ad_name
     *
     * @param adName the value for tk_order_input_jd.ad_name
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setAdName(String adName) {
        this.adName = adName == null ? null : adName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.channel
     *
     * @return the value of tk_order_input_jd.channel
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.channel
     *
     * @param channel the value for tk_order_input_jd.channel
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.third_service_from
     *
     * @return the value of tk_order_input_jd.third_service_from
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getThirdServiceFrom() {
        return thirdServiceFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.third_service_from
     *
     * @param thirdServiceFrom the value for tk_order_input_jd.third_service_from
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setThirdServiceFrom(String thirdServiceFrom) {
        this.thirdServiceFrom = thirdServiceFrom == null ? null : thirdServiceFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.pid
     *
     * @return the value of tk_order_input_jd.pid
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.pid
     *
     * @param pid the value for tk_order_input_jd.pid
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setPid(String pid) {
        this.pid = pid == null ? null : pid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tk_order_input_jd.site_app
     *
     * @return the value of tk_order_input_jd.site_app
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public String getSiteApp() {
        return siteApp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tk_order_input_jd.site_app
     *
     * @param siteApp the value for tk_order_input_jd.site_app
     *
     * @mbg.generated Wed May 02 10:31:05 CST 2018
     */
    public void setSiteApp(String siteApp) {
        this.siteApp = siteApp == null ? null : siteApp.trim();
    }
}