package com.bt.om.entity;

import java.util.Date;

public class UserOrderTmp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order_tmp.id
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order_tmp.mobile
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order_tmp.order_id
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	private String orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order_tmp.status
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order_tmp.belong
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	private Integer belong;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order_tmp.create_time
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user_order_tmp.update_time
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order_tmp.id
	 * @return  the value of user_order_tmp.id
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order_tmp.id
	 * @param id  the value for user_order_tmp.id
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order_tmp.mobile
	 * @return  the value of user_order_tmp.mobile
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order_tmp.mobile
	 * @param mobile  the value for user_order_tmp.mobile
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order_tmp.order_id
	 * @return  the value of user_order_tmp.order_id
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order_tmp.order_id
	 * @param orderId  the value for user_order_tmp.order_id
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order_tmp.status
	 * @return  the value of user_order_tmp.status
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order_tmp.status
	 * @param status  the value for user_order_tmp.status
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order_tmp.belong
	 * @return  the value of user_order_tmp.belong
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public Integer getBelong() {
		return belong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order_tmp.belong
	 * @param belong  the value for user_order_tmp.belong
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public void setBelong(Integer belong) {
		this.belong = belong;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order_tmp.create_time
	 * @return  the value of user_order_tmp.create_time
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order_tmp.create_time
	 * @param createTime  the value for user_order_tmp.create_time
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_order_tmp.update_time
	 * @return  the value of user_order_tmp.update_time
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_order_tmp.update_time
	 * @param updateTime  the value for user_order_tmp.update_time
	 * @mbg.generated  Tue Nov 20 17:13:46 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}