package com.bt.om.mapper;

import com.bt.om.entity.AppDownload;

public interface AppDownloadMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	int insert(AppDownload record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	int insertSelective(AppDownload record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	AppDownload selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	int updateByPrimaryKeySelective(AppDownload record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download
	 * @mbg.generated  Sat Jul 14 16:35:31 CST 2018
	 */
	int updateByPrimaryKey(AppDownload record);

	AppDownload selectLastest(String version);
}