package com.bt.om.mapper;

import com.bt.om.entity.AppDownloadLogs;

public interface AppDownloadLogsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download_logs
	 * @mbg.generated  Fri Aug 03 13:19:44 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download_logs
	 * @mbg.generated  Fri Aug 03 13:19:44 CST 2018
	 */
	int insert(AppDownloadLogs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download_logs
	 * @mbg.generated  Fri Aug 03 13:19:44 CST 2018
	 */
	int insertSelective(AppDownloadLogs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download_logs
	 * @mbg.generated  Fri Aug 03 13:19:44 CST 2018
	 */
	AppDownloadLogs selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download_logs
	 * @mbg.generated  Fri Aug 03 13:19:44 CST 2018
	 */
	int updateByPrimaryKeySelective(AppDownloadLogs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table app_download_logs
	 * @mbg.generated  Fri Aug 03 13:19:44 CST 2018
	 */
	int updateByPrimaryKey(AppDownloadLogs record);
}