package com.bt.om.mapper;

import java.util.List;

import com.bt.om.entity.Banner;

public interface BannerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banner
	 * @mbg.generated  Sat Jul 28 08:55:13 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banner
	 * @mbg.generated  Sat Jul 28 08:55:13 CST 2018
	 */
	int insert(Banner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banner
	 * @mbg.generated  Sat Jul 28 08:55:13 CST 2018
	 */
	int insertSelective(Banner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banner
	 * @mbg.generated  Sat Jul 28 08:55:13 CST 2018
	 */
	Banner selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banner
	 * @mbg.generated  Sat Jul 28 08:55:13 CST 2018
	 */
	int updateByPrimaryKeySelective(Banner record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table banner
	 * @mbg.generated  Sat Jul 28 08:55:13 CST 2018
	 */
	int updateByPrimaryKey(Banner record);

	List<Banner> selectAll(Integer type);
	
	List<Banner> selectForApp(Integer type);
	
	List<Banner> selectCampaign(Integer size);
	
	List<Banner> selectForXcx(Integer type);
}