package com.bt.om.mapper;

import java.util.List;

import com.bt.om.entity.Hotword;

public interface HotwordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotword
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotword
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    int insert(Hotword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotword
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    int insertSelective(Hotword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotword
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    Hotword selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotword
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    int updateByPrimaryKeySelective(Hotword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotword
     *
     * @mbg.generated Thu Oct 25 19:12:57 CST 2018
     */
    int updateByPrimaryKey(Hotword record);
    
    List<Hotword> selectAll();
}