package com.bt.om.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.session.RowBounds;

import com.bt.om.entity.Invitation;
import com.bt.om.entity.UserOrder;

public interface InvitationMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Fri May 25 17:39:15 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Fri May 25 17:39:15 CST 2018
	 */
	int insert(Invitation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Fri May 25 17:39:15 CST 2018
	 */
	int insertSelective(Invitation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Fri May 25 17:39:15 CST 2018
	 */
	Invitation selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Fri May 25 17:39:15 CST 2018
	 */
	int updateByPrimaryKeySelective(Invitation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table invitation
	 * @mbg.generated  Fri May 25 17:39:15 CST 2018
	 */
	int updateByPrimaryKey(Invitation record);

	List<Invitation> findByMobileFriend(Invitation invitation);
	
	String haveInvitation(Invitation invitation);
	
	List<Invitation> selectInvitationList(Invitation invitation);
	
	List<Invitation> selectUnValidInvitationList();
	
	int selectByMobileFriendCount(Map<String, Object> searchMap);

    List<Invitation> selectByMobileFriendList(Map<String, Object> searchMap, RowBounds rowBounds);
	
  //手工统计邀请奖励
    List<Invitation> selectManualInviteJiangli(Map<String, String> map);
}