package com.bt.om.mapper;

import com.bt.om.entity.PddPids;

public interface PddPidsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdd_pids
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdd_pids
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	int insert(PddPids record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdd_pids
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	int insertSelective(PddPids record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdd_pids
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	PddPids selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdd_pids
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	int updateByPrimaryKeySelective(PddPids record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pdd_pids
	 * @mbg.generated  Tue Dec 25 13:09:02 CST 2018
	 */
	int updateByPrimaryKey(PddPids record);
}