package com.bt.om.mapper;

import java.util.List;

import com.bt.om.entity.ProductInfoMid;

public interface ProductInfoMidMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info_mid
     *
     * @mbg.generated Wed Jun 13 18:01:44 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info_mid
     *
     * @mbg.generated Wed Jun 13 18:01:44 CST 2018
     */
    int insert(ProductInfoMid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info_mid
     *
     * @mbg.generated Wed Jun 13 18:01:44 CST 2018
     */
    int insertSelective(ProductInfoMid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info_mid
     *
     * @mbg.generated Wed Jun 13 18:01:44 CST 2018
     */
    ProductInfoMid selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info_mid
     *
     * @mbg.generated Wed Jun 13 18:01:44 CST 2018
     */
    int updateByPrimaryKeySelective(ProductInfoMid record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_info_mid
     *
     * @mbg.generated Wed Jun 13 18:01:44 CST 2018
     */
    int updateByPrimaryKey(ProductInfoMid record);
    
    List<ProductInfoMid> selectAllList();
    
    List<ProductInfoMid> selectByStatusList(Integer ifvalid);
}