package com.bt.om.mapper;

import com.bt.om.entity.ProductFromTkapi;

public interface ProductFromTkapiMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_from_tkapi
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	int insert(ProductFromTkapi record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product_from_tkapi
	 * @mbg.generated  Sat Feb 24 15:09:09 CST 2018
	 */
	int insertSelective(ProductFromTkapi record);
}