package com.bt.om.mapper;

import java.util.List;

import com.bt.om.entity.SearchRecord;

public interface SearchRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    int insert(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    int insertSelective(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    SearchRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    int updateByPrimaryKeySelective(SearchRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table search_record
     *
     * @mbg.generated Fri May 11 14:22:14 CST 2018
     */
    int updateByPrimaryKey(SearchRecord record);
    
    List<SearchRecord> selectByStatusAndTime(SearchRecord searchRecord);
}