package com.bt.om.mapper;

import com.bt.om.entity.SysUserDetail;

public interface SysUserDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_detail
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	int insert(SysUserDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_user_detail
	 * @mbg.generated  Mon Apr 23 15:19:20 CST 2018
	 */
	int insertSelective(SysUserDetail record);
}