package com.bt.om.mapper;

import com.bt.om.entity.TkPids;

public interface TkPidsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_pids
     *
     * @mbg.generated Wed Dec 26 14:50:36 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_pids
     *
     * @mbg.generated Wed Dec 26 14:50:36 CST 2018
     */
    int insert(TkPids record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_pids
     *
     * @mbg.generated Wed Dec 26 14:50:36 CST 2018
     */
    int insertSelective(TkPids record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_pids
     *
     * @mbg.generated Wed Dec 26 14:50:36 CST 2018
     */
    TkPids selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_pids
     *
     * @mbg.generated Wed Dec 26 14:50:36 CST 2018
     */
    int updateByPrimaryKeySelective(TkPids record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tk_pids
     *
     * @mbg.generated Wed Dec 26 14:50:36 CST 2018
     */
    int updateByPrimaryKey(TkPids record);
}