package com.bt.om.mapper;

import java.util.List;
import java.util.Map;

import com.bt.om.entity.User;

public interface UserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Nov 16 19:53:17 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Nov 16 19:53:17 CST 2018
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Nov 16 19:53:17 CST 2018
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Nov 16 19:53:17 CST 2018
	 */
	User selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Nov 16 19:53:17 CST 2018
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Fri Nov 16 19:53:17 CST 2018
	 */
	int updateByPrimaryKey(User record);

	User selectByMobile(String mobile);
	
	List<User> selectByAlipay(String alipay);
	
	User selectByTaInviteCode(String taInviteCode);
	
	User selectByMyInviteCode(String myInviteCode);
	
	int updateHongbao(User record);
	
	List<User> selectAll();
	
	User selectByTaobaoIdAndPid(Map<String,String> map);
}